services:

  tomcat:
    build: .
    container_name: tomcat-jenkins
    ports: 
      - "8080:8080"
    networks:
      - monitoring
    volumes:
      - ./jenkins_home:/var/jenkins_home

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge